### ISSUE TITLE
Unauthorized when trying to get transaction ID

### ISSUE THREAD

**Issue by Vincenttbk** [paypal/PayPal-NET-SDK#106]
Im trying to get a transaction ID while making payment.

Everything seems to be working fine on the sandbox but when i transfer to live, everything is not working.

Here are the information
PayId: PAY-9AD55367K99802132KV7JQBI
The remote server returned an error: (401) Unauthorized. at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
 at PayPal.PayPalResource.ConfigureAndExecute[T](Dictionary`2 config, IAPICallPreHandler apiCallPreHandler, HttpMethod httpMethod, String resourcePath)
 at PayPal.Api.Payment.Get(APIContext apiContext, String paymentId)
 at service.service.addPayId(Booking bookInfo) in c:\inetpub\wwwroot\service\service.svc.cs:line 725

Hope I can get some help here.

**Comment by jziaja** [comment]
Hi @Vincenttbk, just to make sure, is your application setup to use your **live** REST app credentials when you request an access token?

**Comment by jziaja** [comment]
@Vincenttbk, are you still encountering this issue?

**Comment by jziaja** [comment]
Closing due to inactivity. If you're still experiencing this problem, I'd recommend contacting [Merchant Technical Support](https://www.paypal.com/mts) to talk to someone directly. Thanks!

**Comment by Vincenttbk** [comment]
Opps, Sorry, Was away for a awhile. currently it has been fixed!

Once again! Sorry for the delay
