### ISSUE TITLE
403 when fetching plans

### ISSUE THREAD

**Issue by tofutim** [paypal/PayPal-NET-SDK#161]
I am using

```
                var config = PayPal.Api.ConfigManager.Instance.GetProperties();
                var accessToken = new PayPal.Api.OAuthTokenCredential(config).GetAccessToken();
                var apiContext = new PayPal.Api.APIContext(accessToken);
                var plan = PayPal.Api.Plan.Get(apiContext, lastPayment.subscrid);
                var terms = plan.terms;
```

to get subscription information given an subscrid. However, at the call for Plan.Get, I get a 403 Forbidden even though it seems I should be able to get this info.  

![image](https://cloud.githubusercontent.com/assets/157766/15408841/02a3eade-1dc7-11e6-9a0a-9637eaf12e4c.png)

Should I be using something other the plan? Did I miss enabling something? Here is how my API page looks:

![image](https://cloud.githubusercontent.com/assets/157766/15408855/16edeee0-1dc7-11e6-96bb-d08fb15422a6.png)

**Comment by tofutim** [comment]
I got a bit further on this after I realized that I do not have plans but instead subscriptions that start with I-xxxxx. So I switched to Paypal.Api.Agreement.Get(apiContext, subscrid) - in this case my subscrid looks like I-FF4XU2D6NTH2 - but after the call I end up with

> PayPal.HttpException: The remote server returned an error: (403) Forbidden.
>    at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
>    at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader)
>    at PayPal.Api.Agreement.Get(APIContext apiContext, String agreementId)
>

**Comment by tofutim** [comment]
More info

{"name":"REQUIRED_SCOPE_MISSING","message":"Access token does not have required scope","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#REQUIRED_SCOPE_MISSING","debug_id":"e541100535601"}

How do get the right scope?

**Comment by tofutim** [comment]
this suggest there is a place I can set "Advanced capabilities"

http://stackoverflow.com/questions/27049971/paypal-rest-api-php-sdk-billing-i-get-error-required-scope-missing

but I cannot find that page!

**Comment by tofutim** [comment]
I found the Advanced capabilities, but now the error is

{
	"status": 400,
	"duration_time": 149,
	"body": {
		"message": "Subscription Profiles not supported by Recurring Payment APIs.",
		"debug_id": "3d3f355d33701",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#SUBSCRIPTION_UNMAPPED_ERROR",
		"name": "SUBSCRIPTION_UNMAPPED_ERROR"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "246",
		"Content-Language": "*",
		"CORRELATION-ID": "3d3f355d33701",
		"Date": "Thu, 19 May 2016 22:07:58 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "3d3f355d33701",
		"PROXY_SERVER_INFO": "host\\u003ddcg11javapapi3990.dcg11.slc.paypalinc.com;threadId\\u003d375",
		"Content-Type": "application/json"
	}
}
and it seems insurmountable. :(
