### ISSUE TITLE
PayPal.PayPalException: Retried 3 times.... - Error in production

### ISSUE THREAD

**Issue by TomGullen** [paypal/PayPal-NET-SDK#309]
### General information

* SDK/Library version: 1.9.1
* Environment: Production
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: ASP.net framework 4.7, C#

### Issue description

My payments work fine in sandbox, but when moving to production we receive the following exception on our webhook receiver:

`PayPal.PayPalException: Retried 3 times.... Exception in PayPal.HttpConnection.Execute(). Check log for more details.
   at PayPal.Api.HttpConnection.Execute(String payLoad, HttpWebRequest httpRequest)
   at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader)
   at PayPal.Api.OAuthTokenCredential.GenerateOAuthToken()
   at PayPal.Api.OAuthTokenCredential.GetAccessToken()
   at C3.Code.Helpers.Payments.Paypal.Webhooks.HandleWebhookRequest(HttpContext context) in C:\Dropbox\Dropbox (Scirra Ltd)\Tom\C3 Website\C3Alpha2\Code\Helpers\Payments\Paypal\Webhook.cs:line 78`

The line of code this refers to is:

` var accessToken = new OAuthTokenCredential(
                    Settings.Payments.Paypal.PaypalBraintreeAppClientID,
                    Settings.Payments.Paypal.PaypalBraintreeAppSecret,
                    config).GetAccessToken();`

I have checked our production server returns `PayPal_Connection_OK` on TLS tests.

This information may also be pertinent - when I visit the webhook URL directly on our test environment, no errors are thrown.  When I visit the webhook URL directly in production, it throws the exception:

`PayPal.IdentityException: The remote server returned an error: (401) Unauthorized.
   at PayPal.Api.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload, String endpoint, Boolean setAuthorizationHeader)
   at PayPal.Api.OAuthTokenCredential.GenerateOAuthToken()
   at PayPal.Api.OAuthTokenCredential.GetAccessToken()
   at C3.Code.Helpers.Payments.Paypal.Webhooks.HandleWebhookRequest(HttpContext context) in C:\Dropbox\Dropbox (Scirra Ltd)\Tom\C3 Website\C3Alpha2\Code\Helpers\Payments\Paypal\Webhook.cs:line 132
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

**Comment by xiaoleih41** [comment]
Do you have a debug ID? Have you update all the credentials with live credentials?

**Comment by TomGullen** [comment]
Thanks for looking into it - have since solved it.  There were a few issues, the main one being a Cloudflare HTTP 1000 error.  Fixing that seems to of solved everything.
