### ISSUE TITLE
Exception during credit card payments due to Paypal REST API masking expiration date

### ISSUE THREAD

**Issue by dan655t** [paypal/PayPal-NET-SDK#374]
As of the last few hours the paypal REST API started to return the expiration month as an "x" or "xx" instead of an integer between 1 and 12.  This is causing the following exception to be thrown while deserializing the response into a CreditCard object.  

Could not convert string to integer: x. Path 'payer.funding_instruments[0].credit_card.expire_month', line 1, position 289.

at PayPal.PayPalResource.ConfigureAndExecute[T](Dictionary`2 config, IAPICallPreHandler apiCallPreHandler, HttpMethod httpMethod, String resourcePath)
   at PayPal.PayPalResource.ConfigureAndExecute[T](APIContext apiContext, HttpMethod httpMethod, String resource, String payload)
   at PayPal.Api.Payments.Payment.Create(APIContext apiContext)

**Comment by dan655t** [comment]
We solved this by updating to the latest version.
